export const ALL_JOBS = [
  {id:'corporate-remote',name:'Corporate Remote Worker',emoji:'💻',wage:32,taxType:'W2',taxRate:0.22,effectDescription:'Stable income, occasional burnout',flavorText:'Camera off, pants off, productivity off',tier:'good'},
  {id:'nurse',name:'Nurse',emoji:'🏥',wage:35,taxType:'W2',taxRate:0.22,effectDescription:'Stable income, high stress',flavorText:'Saving lives but cant save yourself',tier:'good'},
  {id:'engineer',name:'Engineer',emoji:'🛠️',wage:45,taxType:'W2',taxRate:0.22,effectDescription:'High stable income',flavorText:'Building things and burning out',tier:'good'},
  {id:'accountant',name:'Accountant',emoji:'📊',wage:30,taxType:'W2',taxRate:0.22,effectDescription:'Stable income',flavorText:'Numbers dont lie but your boss does',tier:'good'},
  {id:'marketing-mgr',name:'Marketing Manager',emoji:'📣',wage:34,taxType:'W2',taxRate:0.22,effectDescription:'Stable income',flavorText:'Making things go viral except your paycheck',tier:'good'},
  {id:'hr-specialist',name:'HR Specialist',emoji:'👥',wage:28,taxType:'W2',taxRate:0.22,effectDescription:'Stable income',flavorText:'Pretending to care professionally',tier:'good'},
  {id:'software-dev',name:'Software Developer',emoji:'👨‍💻',wage:48,taxType:'W2',taxRate:0.22,effectDescription:'Highest stable income',flavorText:'Debugging code and your life simultaneously',tier:'good'},
  {id:'project-mgr',name:'Project Manager',emoji:'📋',wage:40,taxType:'W2',taxRate:0.22,effectDescription:'High stable income',flavorText:'Herding cats professionally',tier:'good'},
  {id:'teacher',name:'Teacher',emoji:'🍎',wage:27,taxType:'W2',taxRate:0.22,effectDescription:'Stable but low income',flavorText:'Teaching others what you barely survived',tier:'good'},
  {id:'office-mgr',name:'Office Manager',emoji:'🏢',wage:29,taxType:'W2',taxRate:0.22,effectDescription:'Stable income',flavorText:'The only one holding this place together',tier:'good'},
  {id:'financial-analyst',name:'Financial Analyst',emoji:'💰',wage:42,taxType:'W2',taxRate:0.22,effectDescription:'High stable income',flavorText:'Analyzing everyones money but yours',tier:'good'},
  {id:'healthcare-admin',name:'Healthcare Administrator',emoji:'🏥',wage:36,taxType:'W2',taxRate:0.22,effectDescription:'Stable income',flavorText:'Paperwork and panic attacks',tier:'good'},
  {id:'it-specialist',name:'IT Specialist',emoji:'🖥️',wage:38,taxType:'W2',taxRate:0.22,effectDescription:'Stable income',flavorText:'Have you tried turning it off and on again?',tier:'good'},
  {id:'call-center',name:'Call Center Agent',emoji:'📞',wage:18,taxType:'W2',taxRate:0.18,effectDescription:'Moderate steady income',flavorText:'Please hold while I hold back tears',tier:'bad'},
  {id:'retail-mgr',name:'Retail Manager',emoji:'🛍️',wage:22,taxType:'W2',taxRate:0.18,effectDescription:'Moderate steady income',flavorText:'The customer is NOT always right',tier:'bad'},
  {id:'warehouse-supervisor',name:'Warehouse Supervisor',emoji:'📦',wage:21,taxType:'W2',taxRate:0.18,effectDescription:'Moderate steady income',flavorText:'My back, my knees, my will to live',tier:'bad'},
  {id:'delivery-driver',name:'Delivery Driver',emoji:'🚚',wage:20,taxType:'W2',taxRate:0.18,effectDescription:'Moderate steady income',flavorText:'Your back hurts but the tips help',tier:'bad'},
  {id:'admin-assistant',name:'Administrative Assistant',emoji:'📋',wage:19,taxType:'W2',taxRate:0.18,effectDescription:'Moderate steady income',flavorText:'Organizing someone elses life',tier:'bad'},
  {id:'bank-teller',name:'Bank Teller',emoji:'🏦',wage:18,taxType:'W2',taxRate:0.18,effectDescription:'Moderate steady income',flavorText:'Handling money you cant keep',tier:'bad'},
  {id:'customer-service',name:'Customer Service Representative',emoji:'💬',wage:17,taxType:'W2',taxRate:0.18,effectDescription:'Moderate steady income',flavorText:'Smiling through the chaos',tier:'bad'},
  {id:'security-guard',name:'Security Guard',emoji:'🛡️',wage:19,taxType:'W2',taxRate:0.18,effectDescription:'Moderate steady income',flavorText:'Guarding everything except your peace',tier:'bad'},
  {id:'medical-assistant',name:'Medical Assistant',emoji:'🩺',wage:20,taxType:'W2',taxRate:0.18,effectDescription:'Moderate steady income',flavorText:'Open wide and pray for benefits',tier:'bad'},
  {id:'receptionist',name:'Receptionist',emoji:'🏢',wage:17,taxType:'W2',taxRate:0.18,effectDescription:'Moderate steady income',flavorText:'Gatekeeping the entire office',tier:'bad'},
  {id:'shift-supervisor',name:'Shift Supervisor',emoji:'⏰',wage:21,taxType:'W2',taxRate:0.18,effectDescription:'Moderate steady income',flavorText:'All the responsibility, half the pay',tier:'bad'},
  {id:'factory-worker',name:'Factory Worker',emoji:'🏭',wage:20,taxType:'W2',taxRate:0.18,effectDescription:'Moderate steady income',flavorText:'Rinse and repeat until retirement',tier:'bad'},
  {id:'fast-food',name:'Fast Food Worker',emoji:'🍔',wage:15,taxType:'W2',taxRate:0.15,effectDescription:'Low income, unstable',flavorText:'Sir this is a Wendys',tier:'bad'},
  {id:'retail-associate',name:'Retail Associate',emoji:'🛍️',wage:15,taxType:'W2',taxRate:0.15,effectDescription:'Low income, unstable',flavorText:'Folding clothes that will be ruined in 5 mins',tier:'bad'},
  {id:'gig-driver',name:'Gig Driver',emoji:'🚗',wage:22,wageDisplay:'$8-$35/hr variable',taxType:'1099',taxRate:0.35,effectDescription:'Unpredictable income, chance for BIG BREAK 💥',flavorText:'Made $100… kept $12 after gas and life choices',tier:'good'},
  {id:'house-cleaner',name:'House Cleaner',emoji:'🧽',wage:16,taxType:'W2',taxRate:0.15,effectDescription:'Low income, physical work',flavorText:'Found something weird under the bed...',tier:'bad'},
  {id:'dishwasher',name:'Dishwasher',emoji:'🍽️',wage:15,taxType:'W2',taxRate:0.15,effectDescription:'Low income, physical work',flavorText:'Scrubbing plates and scrubbing by',tier:'bad'},
  {id:'stocker',name:'Stocker',emoji:'📦',wage:15,taxType:'W2',taxRate:0.15,effectDescription:'Low income, physical work',flavorText:'Night shifts and weird customers',tier:'bad'},
  {id:'day-labor',name:'Day Labor Worker',emoji:'🛠️',wage:17,taxType:'W2',taxRate:0.15,effectDescription:'Low income, unstable',flavorText:'Heavy lifting for light pay',tier:'bad'},
  {id:'gas-station',name:'Gas Station Clerk',emoji:'⛽',wage:15,taxType:'W2',taxRate:0.15,effectDescription:'Low income, unstable',flavorText:'Selling lottery tickets you wish you won',tier:'bad'},
  {id:'lawn-care',name:'Lawn Care Worker',emoji:'🌱',wage:16,taxType:'W2',taxRate:0.15,effectDescription:'Low income, physical work',flavorText:'Making yards pretty while yours falls apart',tier:'bad'},
  {id:'warehouse-worker',name:'Warehouse Worker',emoji:'📦',wage:17,taxType:'W2',taxRate:0.15,effectDescription:'Low income, physical work',flavorText:'Permanent stress temporary paycheck',tier:'bad'},
  {id:'babysitting',name:'Babysitting / Odd Jobs',emoji:'👶',wage:15,taxType:'1099',taxRate:0.3,effectDescription:'Low income, unstable',flavorText:'Raising other peoples kids for minimum wage',tier:'bad'},
  {id:'thrift-flipper',name:'Thrift Flipper',emoji:'🧢',wage:12,taxType:'1099',taxRate:0.3,effectDescription:'Low income, unstable',flavorText:'One persons trash is your income',tier:'bad'},
  {id:'streamer',name:'Streamer',emoji:'🎮',wage:20,wageDisplay:'$0-$40/hr variable',taxType:'1099',taxRate:0.35,effectDescription:'Unpredictable income, chance for BIG BREAK 💥',flavorText:'Going live to 2 people… but one viral moment changes everything',tier:'good'},
  {id:'content-creator',name:'Content Creator',emoji:'📱',wage:28,wageDisplay:'$5-$50/hr variable',taxType:'1099',taxRate:0.35,effectDescription:'Unpredictable income, chance for BIG BREAK 💥',flavorText:'Dancing for pennies until the brand deal hits',tier:'good'},
  {id:'freelancer',name:'Freelancer',emoji:'💻',wage:40,wageDisplay:'$20-$60/hr variable',taxType:'1099',taxRate:0.35,effectDescription:'Unpredictable income, chance for BIG BREAK 💥',flavorText:'Chasing invoices instead of dreams',tier:'good'},
  {id:'small-biz',name:'Small Business Owner',emoji:'🛍️',wage:45,wageDisplay:'$10-$80/hr variable',taxType:'1099',taxRate:0.35,effectDescription:'Unpredictable income, chance for BIG BREAK 💥',flavorText:'You invested in yourself… one big deal changes everything',tier:'good'},
  {id:'online-seller',name:'Online Seller',emoji:'📦',wage:30,wageDisplay:'$15-$45/hr variable',taxType:'1099',taxRate:0.35,effectDescription:'Unpredictable income, chance for BIG BREAK 💥',flavorText:'Packing orders at 3 AM',tier:'good'},
  {id:'dropshipper',name:'Dropshipper',emoji:'📊',wage:35,wageDisplay:'$0-$70/hr variable',taxType:'1099',taxRate:0.35,effectDescription:'Unpredictable income, chance for BIG BREAK 💥',flavorText:'Selling things youve never even seen',tier:'good'},
  {id:'social-media-mgr',name:'Social Media Manager',emoji:'📣',wage:30,wageDisplay:'$20-$40/hr variable',taxType:'1099',taxRate:0.35,effectDescription:'Unpredictable income, chance for BIG BREAK 💥',flavorText:'Chronically online for a living',tier:'good'},
  {id:'photographer',name:'Photographer',emoji:'📸',wage:50,wageDisplay:'$25-$75/hr variable',taxType:'1099',taxRate:0.35,effectDescription:'Unpredictable income, chance for BIG BREAK 💥',flavorText:'Capturing moments, missing paychecks',tier:'good'},
  {id:'hair-stylist',name:'Hair Stylist',emoji:'💇‍♀️',wage:35,wageDisplay:'$20-$50/hr variable',taxType:'1099',taxRate:0.35,effectDescription:'Unpredictable income, chance for BIG BREAK 💥',flavorText:'Part-time therapist, full-time artist',tier:'good'},
  {id:'nail-tech',name:'Nail Tech',emoji:'💅',wage:32,wageDisplay:'$18-$45/hr variable',taxType:'1099',taxRate:0.35,effectDescription:'Unpredictable income, chance for BIG BREAK 💥',flavorText:'Breathing acrylic dust for the bag',tier:'good'},
  {id:'personal-trainer',name:'Personal Trainer',emoji:'🏋️‍♀️',wage:43,wageDisplay:'$25-$60/hr variable',taxType:'1099',taxRate:0.35,effectDescription:'Unpredictable income, chance for BIG BREAK 💥',flavorText:'Getting paid to yell at people',tier:'good'},
  {id:'coach-consultant',name:'Coach / Consultant',emoji:'🧠',wage:65,wageDisplay:'$30-$100/hr variable',taxType:'1099',taxRate:0.35,effectDescription:'Unpredictable income, chance for BIG BREAK 💥',flavorText:'Selling advice you barely follow yourself',tier:'good'},
];

export const TILES = [
  {id:0,name:'The Journey Begins',category:'start',actionText:'Ready to trip through life?',effect:'none'},
  {id:1,name:'Your Ex Texted',category:'heartbreak',actionText:'Take a shot or skip a turn',effect:'skip'},
  {id:3,name:'Car Broke Down',category:'chaos',actionText:'Move back 1 space',effect:'move',effectValue:-1},
  {id:4,name:'New Haircut, New You',category:'glowup',actionText:'Roll again!',effect:'roll_again'},
  {id:5,name:'Found $20 in Old Jeans',category:'blessing',actionText:'Move ahead 1 space',effect:'move',effectValue:1},
  {id:6,name:'Got Ghosted Again',category:'heartbreak',actionText:'Skip next turn',effect:'skip'},
  {id:7,name:'WILD CARD',category:'wildcard',actionText:'Host picks your fate',effect:'none'},
  {id:9,name:'Started Therapy',category:'glowup',actionText:'Move ahead 3 spaces',effect:'move',effectValue:3},
  {id:10,name:'💸 TAX SEASON',category:'tax',actionText:'The IRS has entered the chat. ALL players get taxed!',effect:'tax'},
  {id:11,name:'Stranger Paid for Coffee',category:'blessing',actionText:'Move ahead 1 space',effect:'move',effectValue:1},
  {id:12,name:'Caught Them Cheating',category:'heartbreak',actionText:'Move back 3 spaces',effect:'move',effectValue:-3},
  {id:14,name:'WILD CARD',category:'wildcard',actionText:'Swap places with any player',effect:'none'},
  {id:15,name:'Gym Glow Up Era',category:'glowup',actionText:'Roll again!',effect:'roll_again'},
  {id:16,name:'Identity Stolen',category:'chaos',actionText:'Move back 2 spaces',effect:'move',effectValue:-2},
  {id:17,name:'Dream Job Called Back',category:'blessing',actionText:'Move ahead 3 spaces',effect:'move',effectValue:3},
  {id:18,name:'Toxic Friend Exposed',category:'heartbreak',actionText:'Skip a turn',effect:'skip'},
  {id:20,name:'💸 TAX SEASON',category:'tax',actionText:'Uncle Sam wants his cut. ALL players get taxed!',effect:'tax'},
  {id:21,name:'WILD CARD',category:'wildcard',actionText:'Everyone moves back 1 except you',effect:'none'},
  {id:22,name:'Apartment Flooded',category:'chaos',actionText:'Move back 2 spaces',effect:'move',effectValue:-2},
  {id:23,name:'Met Your Person',category:'blessing',actionText:'Move ahead 3 spaces',effect:'move',effectValue:3},
  {id:24,name:'Wedding Called Off',category:'heartbreak',actionText:'Move back 3 spaces',effect:'move',effectValue:-3},
  {id:26,name:'Wrote Your First Book',category:'glowup',actionText:'Move ahead 2 spaces',effect:'move',effectValue:2},
  {id:27,name:'Lost Your Keys... Again',category:'chaos',actionText:'Skip a turn',effect:'skip'},
  {id:28,name:'💸 TAX SEASON',category:'tax',actionText:'Final tax hit before the finish! ALL players get taxed!',effect:'tax'},
  {id:29,name:'You Made It, Babe!',category:'finish',actionText:'Winner winner!',effect:'none'},
  {id:30,name:'Rent Went Up 😬',category:'money_loss',actionText:'Rent went up this month...',effect:'money_loss',effectValue:-150},
  {id:31,name:'Utility Bill Shock ⚡',category:'money_loss',actionText:'Utility bill way higher than expected',effect:'money_loss',effectValue:-100},
  {id:32,name:'Internet Bill Up',category:'money_loss',actionText:'Internet bill randomly increased',effect:'money_loss',effectValue:-20},
  {id:33,name:'Forgot a Subscription 💸',category:'money_loss',actionText:'Subscription you forgot about hit again',effect:'money_loss',effectValue:-25},
  {id:34,name:'Late Fee 😒',category:'money_loss',actionText:'Late fee added to your bill',effect:'money_loss',effectValue:-35},
  {id:35,name:'Gas Prices Spike ⛽',category:'money_loss',actionText:'Gas prices are insane right now',effect:'money_loss',effectValue:-50},
  {id:36,name:'Car Maintenance 🛠️',category:'money_loss',actionText:'Car needs maintenance... again',effect:'money_loss',effectValue:-150},
  {id:37,name:'Flat Tire 😭',category:'money_loss',actionText:"Flat tire… and you're already late for work",effect:'money_loss',effectValue:-100},
  {id:38,name:'Speeding Ticket 🚓',category:'money_loss',actionText:'Caught going 15 over...',effect:'money_loss',effectValue:-275},
  {id:39,name:'Car Got Towed 😭',category:'money_loss',actionText:'Towed… pay to get it back',effect:'money_loss',effectValue:-350},
  {id:40,name:'Doctor Visit 🏥',category:'money_loss',actionText:'Doctor visit… not covered by insurance',effect:'money_loss',effectValue:-700},
  {id:41,name:'Prescription Cost 💊',category:'money_loss',actionText:'Prescription cost hits different',effect:'money_loss',effectValue:-300},
  {id:42,name:'Dental Expense 😬',category:'money_loss',actionText:'Unexpected dental expense',effect:'money_loss',effectValue:-500},
  {id:43,name:'Retail Therapy 🛍️',category:'money_loss',actionText:'Retail therapy got you again',effect:'money_loss',effectValue:-450},
  {id:44,name:'Impulse Buy 😅',category:'money_loss',actionText:'Impulse buy regret is real',effect:'money_loss',effectValue:-200},
  {id:45,name:'Ordered Food Again 🍔',category:'money_loss',actionText:'Ordered food instead of cooking',effect:'money_loss',effectValue:-20},
  {id:46,name:'Boredom Spending',category:'money_loss',actionText:'Spent money out of pure boredom',effect:'money_loss',effectValue:-25},
  {id:47,name:'TikTok Made Me Buy It 😭',category:'money_loss',actionText:'TikTok made you buy it...',effect:'money_loss',effectValue:-60},
  {id:48,name:'Credit Card Interest 😩',category:'money_loss',actionText:'Credit card interest hit hard',effect:'money_loss',effectValue:-28},
  {id:49,name:'Mystery Bank Fee',category:'money_loss',actionText:"Bank fee you didn't understand",effect:'money_loss',effectValue:-30},
  {id:50,name:'Double Charged 💀',category:'money_loss',actionText:'Payment processed twice!',effect:'money_loss',effectValue:-150},
  {id:51,name:'Low Balance Fee 😒',category:'money_loss',actionText:'Low balance fee hit again',effect:'money_loss',effectValue:-35},
  {id:52,name:'Helped Someone Out 💔',category:'money_loss',actionText:'Gave money to someone who needed it',effect:'money_loss',effectValue:-5},
  {id:53,name:'Bought a Meal ❤️',category:'money_loss',actionText:'Bought someone a meal',effect:'money_loss',effectValue:-12},
  {id:54,name:'TikTok Gifts 😭',category:'money_loss',actionText:'Threw too many TikTok gifts',effect:'money_loss',effectValue:-100},
  {id:55,name:'Parking Ticket 🅿️',category:'money_loss',actionText:'Forgot to feed the meter',effect:'money_loss',effectValue:-75},
  {id:56,name:'Phone Screen Cracked 📱',category:'money_loss',actionText:'Dropped your phone face down...',effect:'money_loss',effectValue:-200},
  {id:57,name:'Pet Vet Bill 🐾',category:'money_loss',actionText:'Your fur baby needed the vet',effect:'money_loss',effectValue:-400},
  {id:58,name:'Found Money in Your Pocket 😄',category:'money',actionText:'Check those pockets more often!',effect:'money_gain',effectValue:20},
  {id:59,name:'Got Paid Back 💸',category:'money',actionText:'They actually remembered!',effect:'money_gain',effectValue:50},
  {id:60,name:'Cashback Hit Your Account 💳',category:'money',actionText:'Free money is the best money',effect:'money_gain',effectValue:25},
  {id:61,name:"Didn't Order Food for Once 🍔",category:'money',actionText:'Your wallet thanks you',effect:'money_gain',effectValue:30},
  {id:62,name:'Stuck to Your Budget 📊',category:'money',actionText:'Look at you being responsible!',effect:'money_gain',effectValue:75},
  {id:63,name:'Split Bill Win 😌',category:'money',actionText:'Paid less than expected!',effect:'money_gain',effectValue:40},
  {id:64,name:'Coupon Actually Worked 😭',category:'money',actionText:'Against all odds...',effect:'money_gain',effectValue:15},
  {id:65,name:'Free Drink/Meal Hookup 🍹',category:'money',actionText:'Someone came through!',effect:'money_gain',effectValue:25},
  {id:66,name:'Someone Covered You 🙌',category:'money',actionText:'Good people still exist',effect:'money_gain',effectValue:35},
  {id:67,name:'Tax Refund Hit 🙌',category:'money',actionText:'Uncle Sam gave something back!',effect:'money_gain',effectValue:400},
  {id:68,name:'Extra Hours Paid Off ⏰',category:'money',actionText:'That overtime was worth it',effect:'money_gain',effectValue:150},
  {id:69,name:"Sold Something You Didn't Need 📦",category:'money',actionText:'Declutter = profit',effect:'money_gain',effectValue:120},
  {id:70,name:'Refund Finally Processed 😩',category:'money',actionText:'Only took 3 weeks...',effect:'money_gain',effectValue:200},
  {id:71,name:'Random Discount at Checkout 🛍️',category:'money',actionText:'Price drop surprise!',effect:'money_gain',effectValue:100},
  {id:72,name:'Side Money Came Through 💻',category:'money',actionText:'Hustle pays off sometimes',effect:'money_gain',effectValue:180},
  {id:73,name:'Unexpected Cash Gift 🎁',category:'money',actionText:'Somebody loves you!',effect:'money_gain',effectValue:250},
  {id:74,name:'Bill Was Cheaper Than Expected 😮‍💨',category:'money',actionText:"Wait... that's it??",effect:'money_gain',effectValue:130},
  {id:75,name:'Saved Way More Than Expected 😭',category:'money',actionText:'Accidentally responsible!',effect:'money_gain',effectValue:600},
  {id:76,name:'Someone Came Through BIG 💖',category:'money',actionText:'Real ones show up when it matters',effect:'money_gain',effectValue:700},
  {id:77,name:'Emergency Cost Less Than Expected 😮‍💨',category:'money',actionText:"Could've been so much worse",effect:'money_gain',effectValue:550},
  {id:78,name:'Covered Everything This Month 🙌',category:'money',actionText:'Bills paid, food bought, still breathing',effect:'money_gain',effectValue:500},
  {id:79,name:'Financial Stress Eased Up 😩✨',category:'money',actionText:'Finally catching a break',effect:'money_gain',effectValue:650},
  {id:80,name:'Student Loan Payment Hit 😭',category:'money_loss',actionText:'Sallie Mae never forgets...',effect:'money_loss',effectValue:-300},
  {id:81,name:"Degree Didn't Match the Pay 😬",category:'money_loss',actionText:'4 years for THIS salary?',effect:'money_loss',effectValue:-200},
  {id:82,name:'Burnout… Unpaid Time Off 😩',category:'money_loss',actionText:'Your body said no but bills said yes',effect:'money_loss',effectValue:-250},
  {id:83,name:'Job Relocation Cost You 💼',category:'money_loss',actionText:'New city, new expenses, same stress',effect:'money_loss',effectValue:-400},
  {id:84,name:'Office Politics Cost You 😒',category:'money_loss',actionText:'Someone else got YOUR opportunity',effect:'money_loss',effectValue:-150},
  {id:85,name:'Hours Cut This Week 😬',category:'money_loss',actionText:'Schedule changed without warning',effect:'money_loss',effectValue:-200},
  {id:86,name:'Missed Promotion 😒',category:'money_loss',actionText:'They gave it to someone else...',effect:'money_loss',effectValue:-150},
  {id:87,name:'Shift Cut Last Minute 😩',category:'money_loss',actionText:'Manager changed the schedule again',effect:'money_loss',effectValue:-120},
  {id:88,name:'Called Out Unpaid 😭',category:'money_loss',actionText:"Burnout is real but bills don't care",effect:'money_loss',effectValue:-180},
  {id:89,name:'No Raise This Year 😤',category:'money_loss',actionText:'Job feels stuck… again',effect:'money_loss',effectValue:-100},
  {id:90,name:'Shift Got Canceled 😭',category:'money_loss',actionText:'Already got dressed for nothing',effect:'money_loss',effectValue:-120},
  {id:91,name:'Hours Cut Again 😬',category:'money_loss',actionText:'Boss keeps cutting your schedule',effect:'money_loss',effectValue:-200},
  {id:92,name:'Let Go Unexpectedly 💀',category:'money_loss',actionText:'No warning. No severance. Just gone.',effect:'money_loss',effectValue:-300},
  {id:93,name:'Missed Work… No Pay 😩',category:'money_loss',actionText:"Life happened but the check didn't",effect:'money_loss',effectValue:-150},
  {id:94,name:'Transportation Issue 🚗',category:'money_loss',actionText:"Couldn't get to work today",effect:'money_loss',effectValue:-100},
  {id:104,name:'Laundry Machine Ate Your Quarters',category:'money_loss',actionText:'And your clothes are still wet',effect:'money_loss',effectValue:-15},
  {id:105,name:'Friend Needed Emergency Cash',category:'money_loss',actionText:'You know you are never seeing this again',effect:'money_loss',effectValue:-200},
  {id:106,name:'Accidentally Tipped 30%',category:'money_loss',actionText:'Math is hard under pressure',effect:'money_loss',effectValue:-25},
  {id:107,name:'Streaming Service Price Hike',category:'money_loss',actionText:'They got you again',effect:'money_loss',effectValue:-18},
  {id:108,name:'Lost Your Wallet 😭',category:'money_loss',actionText:'The replacement fees hurt the most',effect:'money_loss',effectValue:-350},
  {id:109,name:'HOA Fee Hit',category:'money_loss',actionText:'Paying to be told what to do',effect:'money_loss',effectValue:-250},
  {id:110,name:'Gym Membership You Never Use',category:'money_loss',actionText:'Maybe next month...',effect:'money_loss',effectValue:-45},
  {id:111,name:'Food Delivery Fee Shock',category:'money_loss',actionText:'The fees cost more than the food',effect:'money_loss',effectValue:-22},
  {id:112,name:'Accidentally Left Lights On',category:'money_loss',actionText:'Your dad was right',effect:'money_loss',effectValue:-40},
  {id:113,name:'Kid Needed School Supplies',category:'money_loss',actionText:'Why are markers so expensive?',effect:'money_loss',effectValue:-80},
  {id:114,name:'Found a Side Gig 💪',category:'money',actionText:'Hustle paying off',effect:'money_gain',effectValue:300},
  {id:115,name:'Got a Raise!',category:'money',actionText:'Finally some recognition',effect:'money_gain',effectValue:200},
  {id:116,name:'Scratch Ticket Win 🎰',category:'money',actionText:"Don't spend it all at once",effect:'money_gain',effectValue:150},
  {id:117,name:'Birthday Money 🎂',category:'money',actionText:'Thanks Grandma!',effect:'money_gain',effectValue:100},
  {id:118,name:'Sold Old Clothes Online',category:'money',actionText:'Decluttering for profit',effect:'money_gain',effectValue:80},
  {id:119,name:'Class Action Settlement Hit',category:'money',actionText:'You forgot you even signed up',effect:'money_gain',effectValue:450},
  {id:120,name:'Neighbor Paid You to Pet Sit',category:'money',actionText:'Getting paid to hang with dogs',effect:'money_gain',effectValue:60},
  {id:121,name:'Won a Bet 😏',category:'money',actionText:'You knew you were right',effect:'money_gain',effectValue:175},
  {id:122,name:'Overtime Approved!',category:'money',actionText:'Tired but richer',effect:'money_gain',effectValue:250},
  {id:123,name:'Random Venmo From Mom 💕',category:'money',actionText:'Moms are the best',effect:'money_gain',effectValue:125},
  {id:124,name:'Best Friend Moved Away',category:'heartbreak',actionText:'Skip a turn to cry',effect:'skip'},
  {id:125,name:'Got a Compliment From a Stranger',category:'blessing',actionText:'Move ahead 1 space',effect:'move',effectValue:1},
  {id:126,name:'Therapy Breakthrough 🧠',category:'glowup',actionText:'Move ahead 2 spaces',effect:'move',effectValue:2},
  {id:127,name:'Roommate Drama 😤',category:'chaos',actionText:'Move back 1 space',effect:'move',effectValue:-1},
  {id:128,name:'WILD CARD',category:'wildcard',actionText:'Truth or Dare',effect:'none'},
  {id:129,name:'Started a Journal ✨',category:'glowup',actionText:'Roll again!',effect:'roll_again'},
  {id:130,name:'Family Drama at Dinner',category:'heartbreak',actionText:'Skip a turn',effect:'skip'},
  {id:131,name:'Random Act of Kindness',category:'blessing',actionText:'Move ahead 2 spaces',effect:'move',effectValue:2},
  {id:132,name:'Phone Died at the Worst Time',category:'chaos',actionText:'Move back 1 space',effect:'move',effectValue:-1},
  {id:133,name:'WILD CARD',category:'wildcard',actionText:'Spin the Wheel',effect:'none'},
];